<?php
//index.php member page
define("INDEX_001", "Mobile phone number");
define("INDEX_009", "The information has not been sent from server.");
define("INDEX_010", "Enter your phone number correctly.");
define("INDEX_011", "This company has been disabled");
define("INDEX_012", "This company does not exist!");
define("INDEX_013", "The message has been sent");
define("INDEX_0133", "The message was not sent, please try again");
//index.title.inc.php member page
define("INDEX_002", "Home");
define("INDEX_003", "About Us");
define("INDEX_004", "Contact Us");
define("INDEX_081", "Change Language");
//index.tail.inc.php member page
define("Tail_001", "All rights reserved");
define("Tail_002", "Daba Co");
define("Tail_003", ".");
//index.register.php member page
define("INDEX_005", "Name");
define("INDEX_006", "Family name");
define("INDEX_007", "E-mail");
//index.login.php member page
define("INDEX_008", "Password");
define("INDEX_014", "Login");
define("INDEX_015", "Via SMS");
define("INDEX_016", "Via Voice Call");
define("INDEX_017", "Your User ID has been disabled");
define("INDEX_018", "Log off");
define("INDEX_019", "Please fill password");
define("INDEXLOGIN_001", "Resend password");
define("INDEXLOGIN_002", "Close");
//status.login.php member page
define("INDEX_0020", "IP");
define("INDEX_0021", "Start time/Finish time");
define("INDEX_0022", "Disconnect");
define("INDEX_0023", "Connect");
define("INDEX_0024", "Your password will be sent via voice Message in a few minutes.");
define("INDEX_0025", "Your password will be sent via SMS in a few minutes.");
define("INDEX_0026", "Enter your phone number to connect to the internet. ");
define("INDEX_0027", "Last connection");
define("INDEX_0028", "Service");
define("INDEX_0029", "Total usage");
define("INDEX_0030", "First connection");
define("INDEX_0031", "Last disconnection");
define("INDEX_0032", "Start time");
define("INDEX_0033", "End time");
define("INDEX_0034", "The password has been sent to you more than three times. Please contact the manager");
define("INDEX_0035", "If you did not receive the password, it can be sent to you again with the two options below");
define("INDEX_0036", "Total");
define("INDEX_0037", "Now");
define("INDEX_0038", "Last day");
define("INDEX_0039", "Last week");
define("INDEX_0040", "Last month");
define("INDEX_0041", "Report Customer");
define("INDEX_0042", "User account");
define("INDEX_0043", "Change password");
define("INDEX_0044", "Enter coupon code here");
define("INDEX_0045", "Please enter the information, correctly.");
define("INDEX_0046", "Information has been updated, successfully.");
define("INDEX_0047", "Your password has been changed, successfully.");
define("INDEX_0048", "Your new password");
define("INDEX_0049", "is");
define("INDEX_0050", "The new password and the confirmation of new password do not match.");
define("INDEX_0051", "The old password you typed does not match the password in the system. Please try again.");
define("INDEX_0052", "dismiss");
define("INDEX_0053", "Problem of texting has happened, please contact support.");
define("INDEX_0054", "The number of users for your company has been finished, please contact support.");
define("INDEX_0055", "The number of calls for your company has been finished, please contact support.");
define("INDEX_0056", "The number of messages has been finished, please buy SMS.");
define("INDEX_0057", "Remaining users");
define("INDEX_0058", "Sms remaining");
define("INDEX_0059", "Remaining calls");
define("INDEX_0060", "Remaining days");
define("INDEX_0061", "Your credit has been finished, please buy credit.");
define("INDEX_0062", "Physical address");
define("INDEX_0063", "Tool");
define("INDEX_0064", "System");
define("INDEX_0065", "Pay");
define("INDEX_0066", "Your account has been disabled");
define("INDEX_0067", "Netband");
define("INDEX_0068", "Netband, A system for managing network bandwidth and internet resources");
define("INDEX_0069", "Please Enter your phone number correctly.");
define("INDEX_0070", "Please wait...");
define("INDEX_0071", "You are out of our network or directly connected to the internet. Please disconnect the internet and try again. If the problem still exists, please contact support.");
define("INDEX_0072", "A problem occurred in registration, please try again.");
define("INDEX_0073", "Please choose a number");
define("INDEX_0074", "Entering new button");
define("INDEX_0075", "No Information");
define("INDEX_0076", "For activating your account please contact support.");
define("INDEX_0077", "Your Nas is not part of company. Please contact support.");
define("INDEX_0078", "This Company does not exist or is inactive!");
define("INDEX_0079", "Username or Password is not correct");
define("INDEX_0080", "Welcome to Admin Panel");
define("INDEX_0081", "Phone number");
define("INDEX_0082", "Change number");
define("INDEX_0083", "Back to Home");
define("INDEX_0084", "To connect to the internet click the button below");
define("INDEX_0085", "You have successfully signed out");
define("INDEX_0086", "Archive");
define("INDEX_0087", "Featured");
define("INDEX_0088", "New password confirmation do not match");
define("INDEX_0089", "Please enter your first name");
define("INDEX_0090", "Please enter your last name");
define("INDEX_0091", "Please enter your email correctly");
define("INDEX_0092", "Gender");
define("INDEX_0093", "Male");
define("INDEX_0094", "Female");
define("INDEX_0095", "Birthday");
define("INDEX_0096", "Confirm payment");
define("INDEX_0097", "Summary of basket");
define("INDEX_0098", "Factor Number");
define("INDEX_0099", "Payment Amount");
define("INDEX_0100", "Token Request");
define("INDEX_0101", "Transaction status");
define("INDEX_0102", "Please choose your date of birth.");
define("INDEX_0103", "Please choose ...");
define("INDEX_0104", "processing ...");
define("INDEX_0105", "Please fill in the required fields.");
define("INDEX_0106", "There is no service for your NAS.");
define("INDEX_0107", "Network trouble. Please try again");
define("INDEX_0108", "Please try again or contact support if there is a problem");
define("INDEX_0109", "Your credit time has been expired. Please renew your service");
define("INDEX_0110", "Your traffic has been finished. Please renew your service");
define("INDEX_0111", "RADIUS run to problem. Please contact support");
define("INDEX_0112", "Your nas does not belong to any company");
define("INDEX_0113", "Your IP not valid");
define("INDEX_0114", "Your account not active");
define("INDEX_0115", "Hotspot is disabled");
define("INDEX_0116", "Contact Info");
define("INDEX_0117", " Service name: ");
define("INDEX_0118", "Total volume");
define("INDEX_0119", "Total service time");
define("INDEX_0120", "Service speed");
define("INDEX_0121", "Timely service");
define("INDEX_0122", "Periodically volume");
define("INDEX_0123", "Maximum connection time");
define("INDEX_0125", "buy volume");
define("INDEX_0126", "buy service");
define("Weekly", "Weekly");
define("Daily", "Daily");
define("Monthly", "Monthly");

//auto login
define("AutoLogin_001","Nothing");
define("AutoLogin_002","Mac");
define("AutoLogin_003","IP");
define("AutoLogin_004","Mac and IP");

// contact.php
define("CONTACT_001","The time of your company package has been expired.");

//index.guide.php
define("GUIDE_001", "A) Entering your mobile phone number.");
define("GUIDE_002", "Enter your mobile phone number");
define("GUIDE_003", "Use English mode.");
define("GUIDE_004", "B) Register");
define("GUIDE_005", "You will just see this page the first time that you login to the system.");
define("GUIDE_006", "Enter your name, family name and E-mail.");
define("GUIDE_007", "C) Login");
define("GUIDE_008", "A SMS will be sent to you containing your password.");
define("GUIDE_009", "Enter your password.");
define("GUIDE_010", "D) Password reminder");
define("GUIDE_011", "If the password was not sent to you through your phone, you can use the Resend Password button. ");
define("GUIDE_012", "(Voice call and SMS)");
define("GUIDE_013", "E) Internet usage status");
define("GUIDE_014", "1) Go to Netband URL.");
define("GUIDE_015", "For example: daba.netband.ir");
define("GUIDE_016", "2) Enter your mobile phone number.");
define("GUIDE_017", "3) Enter your password.");
define("GUIDE_018", "4) You see the internet usage section, which shows your usage.");
define("GUIDE_019", "In this section, you can see the devices that you are connected with.");
define("GUIDE_020", "5) Log out");
define("GUIDE_021", "There is a button at the top of the page. By pressing it, you will log out from the status section.");
define("GUIDE_022", "Connection or disconnection:");
define("GUIDE_023", "At the bottom of the status section, you can see the connection or disconnection button.");
define("GUIDE_024", "Other facilities");
define("GUIDE_025", "About us");
define("GUIDE_026", "This link is in the menu at the top of all the pages.");
define("GUIDE_027", "This page contains information about the company.");
define("GUIDE_028", "Contact us");
define("GUIDE_029", "This link is in the menu at the top of all the pages. ");
define("GUIDE_030", "This page contains address and telephone number of the company. You can contact support.");
define("GUIDE_031", "Multi language");
define("GUIDE_032", "You can change the language easily, by pressing the flag.");
define("GUIDE_033", "Has been Changed Successfully ...");

//define("INDEX_002", "");

//Admin Guide
define("AdminGuide_001", "You can see all the companies here.");
define("AdminGuide_002", "You can see the details, modify or edit the companies, here.");
define("AdminGuide_003", "You can see the defined packages, here.");
define("AdminGuide_004", "You can modify the packages, here.");
define("AdminGuide_005", "You can make a new package by specifying the name, group and kind of package.");
define("AdminGuide_006", "You can see the list of group packages here.");
define("AdminGuide_007", "You can modify the group packages, here.");
define("AdminGuide_008", "You can add a group package here.");
define("AdminGuide_009", "You can make a group package here.");
define("AdminGuide_010", "You can see the company group, here.");
define("AdminGuide_011", "You can modify the company group, here.");
define("AdminGuide_012", "You can make a company group, here.");
define("AdminGuide_013", "You can see the list of all Nas, here.");
define("AdminGuide_014", "You can modify or delete nas, here.");
define("AdminGuide_015", "You can see the list of advertisements defined for users. By clicking on each title , the table will be sorted according to that title.");
define("AdminGuide_016", "You can modify the advertisements, here. You can remove the ad or block it by changing its status.");
define("AdminGuide_017", "You can see the list of advertisements defined for operators. By clicking on each title , the table will be sorted according to that title.");
define("AdminGuide_018", "Choose a name for the advertisement.");
define("AdminGuide_019", "Choose the place of the advertisement. (Top or at the bottom of the page)");
define("AdminGuide_020", "Choose the priority of the advertisement. (Ads will be shown according to their priorities.)");
define("AdminGuide_021", "You can link the advertisement to a web page by entering its URL.");
define("AdminGuide_022", "You can choose if you want the Ad to be shown for the English version or Persian version.");
define("AdminGuide_023", "You can add comments, here.");
define("AdminGuide_024", "You can add the picture for your advertisement.");
define("AdminGuide_025", "At last, click on the save button.");
define("AdminGuide_026", "You can edit or modify the advertisement specifications, here.");
define("AdminGuide_027", "In this table you can see the connection time and traffic volume used by users. By clicking on each title , the table will be sorted according to that title.");
define("AdminGuide_028", "You can search in each column.");
define("AdminGuide_029", "After changing the service for user, the user information related to the previous service will be shown in this table.");
define("AdminGuide_030", "In this table you can see the increments that has been made for users traffic volumes. By clicking on each title , the table will be sorted according to that title.");
define("AdminGuide_031", "In this table you can see the previous service and the current service of users. By clicking on each title , the table will be sorted according to that title.");
define("AdminGuide_032", "In this table you can see the users that have been kicked or locked. By clicking on each title , the table will be sorted according to that title.");
define("AdminGuide_033", "In this table you can see the log of calls and messages that have been sent to users. By clicking on each title , the table will be sorted according to that title.");
define("AdminGuide_034", "In this table you can see the details of users payments to company. By clicking on each title , the table will be sorted according to that title.");
define("AdminGuide_035", "You can specify the maximum time of connection to the internet, here.");
define("AdminGuide_036", "By enabling this button, you can define the available time to access the internet, according to a specific date and time. ");
define("AdminGuide_037", "You can define days for available access time. You can add or remove days.");
define("AdminGuide_038", "You can define the number of concurrent connections, here so that the user can login with different device. (Multi login)");
define("AdminGuide_039", "You can see the list of services that have been defined for users. By clicking on each title , the table will be sorted according to that title.");
define("AdminGuide_040", "You can edit the specifications of the service, here.");
define("AdminGuide_041", "You can set the periodic volume, here. It can be daily, weekly or monthly.");
define("AdminGuide_042", "You can set the volume for the defined periodic volume.");
define("AdminGuide_043", "You can add a child advertisement, here. The child advertisement will be shown after you click on the primary advertisment.");
define("AdminGuide_044", "You can see the messages that the users have sent to you.");
define("AdminGuide_045", "You can mark the messages as read or delete them.");
define("AdminGuide_046", "You can see the list of all users.");
define("AdminGuide_047", "You can edit user information.)");
define("AdminGuide_048", "You can see the list of online users.");
define("AdminGuide_049", "When the users login to the system, the password is sent to them via SMS. You can customize this sms, using this form. ");
define("AdminGuide_050", "Insert the text that will appear before the password.");
define("AdminGuide_051", "Insert the text that will appear after the password.");
define("AdminGuide_052", "You can define the url of a website that you want to be shown as an advertisement. When the users login, they will be redirected to this url.");
define("AdminGuide_053", "You can define a periodic advertisement that will be shown each time in the period specified here.");
define("AdminGuide_054", "You can see menu price list in this table.");
define("AdminGuide_055", "choose a name:");
define("AdminGuide_056", "Specify the price.");
define("AdminGuide_057", "   Number not sent  ");
define("AdminGuide_058", "There was a problem in posting photo");

//admin.login.php login page
define("Login_001", "Login to management");
define("Login_002", "User ID");
define("Login_003", "Password");
define("Login_004", "Login");
//admin.rightMenu.php Admin page
define("Admin_001", "Dashboard");
define("Admin_002", "Companies");
define("Admin_003", "List of all companies");
define("Admin_004", "Add company");
define("Admin_005", "Nas");
define("Admin_006", "List of all Nas");
define("Admin_007", "Add Nas");
define("Admin_008", "Users");
define("Admin_009", "List of all users");
define("Admin_010", "List of online users");
define("Admin_011", "Add user");
define("Admin_012", "Services");
define("Admin_013", "List of all services");
define("Admin_014", "Add service");
define("Admin_015", "Operators");
define("Admin_016", "Reports");
define("Admin_017", "Detailed report of users usage");
define("Admin_018", "Report of increment in users traffic volume");
define("Admin_019", "Real-time report of users");
define("Admin_020", "Users logged in and logged out report");
define("Admin_021", "Report of changes in user's service");
define("Admin_022", "Kick report , Lock User");
define("Admin_023", "Report of total traffic of user");
define("Admin_024", "Users advertisements");
define("Admin_025", "List of users advertisements");
define("Admin_026", "Add advertisement for users");
define("Admin_027", "Companies advertisements");
define("Admin_028", "List of companies advertisements");
define("Admin_029", "Add advertisement for companies");
define("Admin_037", "Archive of user's total traffic report");
define("Admin_038", "Pages");
define("Admin_0381", "Company Menu ");
define("Admin_039", "About Us");
define("Admin_040", "Contact Us");
define("Admin_041", "Users Messages");
define("Admin_042", "Number of successful connections");
define("Admin_043", "Last Users");
define("Admin_044", "High consumption users");
define("Admin_047", "Log report of calls to customers");
define("Admin_048", "Log Report");
define("Admin_049", "Users traffic report");
define("Admin_050", "Report of users payments to company");
define("Admin_051", "Text of the SMS containing password");
define("Admin_052", "Text before password");
define("Admin_053", "Text after password");
define("Admin_054", "Number of all pages");
define("Admin_055", "Setting");
define("Admin_056", "Define admin system");
define("Admin_057", "Dear company manager ");
define("Admin_058", "Welcome to Netband.");
define("Admin_059", "List of sent messages");
define("Admin_060", "Companies payments report");
define("Admin_061", "Report of the number of user connections in the system");
define("Admin_062", "Companies Message");
define("Admin_063", "Modify the text of sent messages");
define("Admin_064", "Mobile users");

//admin.index.php Admin page
define("Admin_030", "Users");
define("Admin_031", "Registered Users");
define("Admin_032", "Online users");
define("Admin_033", "Advertisements");
define("Admin_045", "The number of password reminder messages has ended for today, for retrieving the password please contact the manager.");
define("Admin_046", "The number of password reminder voice calls has ended for today, for retrieving the password please contact the manager");
//admin.title.inc.php Admin page
define("Admin_034", "Welcome");
define("Admin_035", "Logout from system");
//admin.tail.inc.php Admin page
define("Admin_036", "&copy; ". date('Y') ." Hotspot Daba Parsian. ");
//admin.company.*.php Admin page
define("Admin_064", "List of Welcome Messages ");
define("Admin_065", "Text of message");
define("Admin_066", "Add a welcome message");
define("Admin_067", "Text of this language has been added!");
define("Admin_068", "Now the user is active.");
define("Admin_069", "Now the user is inactive.");
define("Admin_070", "Editing was not done.");
define("Admin_071", "Menu price list");
define("Admin_072", "Adding company menu");

define("Company_001", "Row");
define("Company_002", "Company's English name");
define("Company_003", "Company's Persian name");
define("Company_004", "Company ID");
define("Company_005", "Status");
define("Company_006", "Company's Manager Name");
define("Company_007", "Address");
define("Company_008", "Tel number");
define("Company_009", "Web Address");
define("Company_010", "E-mail");
define("Company_011", "Comments");
define("Company_012", "Tools");
define("Company_013", "Change Status");
define("Company_014", "Move Company");
define("Company_015", "Modify Company");
define("Company_016", "Choose page number");
define("Company_017", "Company's Logo");
define("Company_018", "Active");
define("Company_019", "Inactive");
define("Company_020", "Create Company");
define("Company_021", "Move Company");
define("Company_022", "Company name");
define("Company_023", "The name is not valid");
define("Company_024", "Persian name has not been entered correctly");
define("Company_025", "English name has not been entered correctly");
define("Company_026", "address has not benn entered correctly");
define("Company_027", "phone number has not been entered correctly");
define("Company_028", "website has not been entered correctly");
define("Company_029", "E-mail has not been entered correctly");
define("Company_030", "Password has not been entered");
define("Company_031", "Status has not been entered correctly");
define("Company_032", "Company's comments has not been entered correctly");
define("Company_033", "Company's ID has not been entered correctly");
define("Company_034", "Admin moved successfully");
define("Company_035", "Admin did not move");
define("Company_036", "Advertisment moved successfully");
define("Company_037", "Advertisment did not move");
define("Company_038", "Transfer moved successfully");
define("Company_039", "Transfer did not move");
define("Company_040", "radacct moved successfully");
define("Company_041", "radacct did not move");
define("Company_042", "radcheck moved successfully");
define("Company_043", "radcheck did not move");
define("Company_044", "radgroupcheck moved successfully");
define("Company_045", "radgroupcheck did not move");
define("Company_046", "radgroupreply moved successfully");
define("Company_047", "radgroupreply did not move");
define("Company_048", "radhuntgroup moved successfully");
define("Company_049", "radhuntgroup did not move");
define("Company_050", "radpostauth moved successfully");
define("Company_051", "radpostauth did not move ");
define("Company_052", "radreply moved successfully");
define("Company_053", "radreply did not move");
define("Company_054", "radusergroup moved successfully");
define("Company_055", "radusergroup did not move");
define("Company_056", "servicechange moved successfully ");
define("Company_057", "servicechange did not move");
define("Company_058", "services moved successfully ");
define("Company_059", "services did not move");
define("Company_060", "sessions moved successfully ");
define("Company_061", "sessions did not move");
define("Company_062", "User history moved successfully ");
define("Company_063", "User history did not move");
define("Company_064", "User info moved successfully ");
define("Company_065", "User info did not move");
define("Company_066", "Company info moved successfully ");
define("Company_067", "Company info did not move");
define("Company_068", "Backup Email");
define("Company_070", "Backup Name");
define("Company_071", "Backup Family name");
define("Company_072", "Company's email");
define("Company_073", "File Size must lower than 1 mb");
define("Company_074", "File Extension Not Allowed");
define("Company_075", "Please fill all required fields");
define("Company_076", "Added Successfully");
define("Company_077", "Not copy file");
define("Company_078", "There was a problem in creating the company,please contact the system admin");
define("Company_079", "This company name exists");
define("Company_080", "There was a problem when creating the directory");
define("Company_081", "This company name exists");
define("Company_082", "Add company group");
define("Company_083", "Delete company");
define("Company_084", "For the date, you only have to choose the first day of the month.");
define("Company_085", "Company");
define("Company_086", "Edit user information");
define("Company_087", "Modification has been done successfully.");
define("Company_088", "Company Phone");
define("Company_089", "Company's phone number is not correct.");
define("Company_090", "Please enter your birthday correctly");
define("Company_091", "Select your gender");
define("Company_092", "for make a first service of default company`s service, please select the details of that service.");
define("Company_093", "Resolution is not 1180*310. Please try again");
define("Company_094", "Resolution is not 300*167. Please try again");
define("Company_095", "Create guest user for the site when the browser does not support.");
define("Company_096", "Guest name");
define("Company_097", "Guest password");
define("Company_098", "Guest phone");
define("Company_099", "Guest name has not been entered correctly");
define("Company_100", "Guest phone has not been entered correctly");
define("Company_101", "Guest password has not been entered correctly");
define("Company_102", "The entered policy is no correct");
define("Company_103", "Company category");
define("Company_104", "Company category not selected correctly");

//admin.nas.*.php Admin page
define("Nas_001", "Nas IP");
define("Nas_002", "Nas Name");
define("Nas_003", "Type");
define("Nas_004", "Port");
define("Nas_005", "Secret");
define("Nas_006", "Server");
define("Nas_007", "Community");
define("Nas_008", "Delete Nas");
define("Nas_009", "Modify Nas");
define("Nas_010", "Source Nas ID");
define("Nas_011", "Destination Nas ID ");
define("Nas_012", "Before deleting Nas you have to move Nas to another Nas");
define("Nas_013", "Nas IP has not been entered correctly");
define("Nas_014", "Branch's short name has not been entered correctly");
define("Nas_015", "TYPE  Branch has not been entered correctly");
define("Nas_016", "PORT  Branch has not been entered correctly");
define("Nas_017", "Branch code has not been entered correctly");
define("Nas_018", "SERVER Branch has not been entered correctly");
define("Nas_019", "Community Branch has not been entered correctly");
define("Nas_020", "Branch comments has not been entered correctly");
define("Nas_021", "Branch ID has not been entered correctly");
define("Nas_022", "Duplicate NAS IP");
define("Nas_023", "userinfo changed successfully ");
define("Nas_024", "userinfo did not change ");
define("Nas_025", "radhuntgroup was changed successfully ");
define("Nas_026", "radhuntgroup not found ");
define("Nas_027", "nas was changed successfully ");
define("Nas_028", "nas not found ");
define("Nas_029", "Microtik Username");
define("Nas_030", "Mikrotik Password");
define("Nas_031", "IP Local mikrotic");
define("Nas_032", "Microtik Username has not been entered correctly");
define("Nas_033", "Microtik Password has not been entered correctly");
define("Nas_034", "IP Local mikrotik Username has not been entered correctly");
define("Nas_035", "Are you sure you want to delete this Nas?");
define("Nas_036", "Mac Cookie");
define("Nas_037", "Making NAS Public");
define("Nas_038", "Successfully changed");
define("Nas_039", "Green row is a public NAS of system.");
define("Nas_040", "This is a public NAS and it`s not removable!");
define("Nas_041", "The yellow row is a NAS, which has a default service.");
define("Nas_042", "The blue row is a public NAS and default service");
define("Nas_043", "Automatic password");
define("Nas_044", "نام کمپانی");
define("Nas_045", "lat location ");
define("Nas_046", "long location");
define("Nas_047", " موقعیت جغرافیایی را پر کنید.");
define("Nas_048", "تلفن");
define("Nas_049", "آدرس");
define("Nas_050", "آدرس و تلفن را پر کنید.");
define("Nas_051", "Login type");
define("Nas_052", "Default type");
define("Nas_053", "phoneNumber");
define("Nas_054", "coupon");
define("Nas_055", "email");

//admin.service.*.php Admin page
define("Service_001", "Create new service");
define("Service_002", "In this section you can make a new service");
define("Service_003", "Success");
define("Service_004", "Service has been registered successfully");
define("Service_005", "User's service name:");
define("Service_006", "Speed");
define("Service_007", "Choose service period");
define("Service_008", "Daily usage");
define("Service_009", "Weekly usage");
define("Service_0010", "Monthly usage");
define("Service_0011", "Traffic volume amount");
define("Service_0012", "Gigabyte");
define("Service_0013", "Megabyte");
define("Service_0014", "Days");
define("Service_0015", "Hourly service");
define("Service_0016", " Maximum time of connection to the internet (Minute:Hour)");
define("Service_0017", "Specified time in specified days");
define("Service_0018", "Finishing service at a specified date");
define("Service_0019", "Time according to date");
define("Service_0020", "All days in a week");
define("Service_0021", "from");
define("Service_0022", "until");
define("Service_0023", "Dismiss");
define("Service_0024", "Confirm");
define("Service_0025", "Time in day and hour");
define("Service_0026", "For using this option you can choose specific days in a week and dedicate a specific time to it.");
define("Service_0027", "Saturday");
define("Service_0028", "Sunday");
define("Service_0029", "Monday");
define("Service_0030", "Tuesday");
define("Service_0031", "Wednesday");
define("Service_0032", "Thursday");
define("Service_0033", "Friday");
define("Service_0034", "Choose day");
define("Service_0035", "First day");
define("Service_0036", "Second day");
define("Service_0037", "Third day");
define("Service_0038", "Fourth day");
define("Service_0039", "Fifth day");
define("Service_0040", "Sixth day");
define("Service_0041", "Seventh day");
define("Service_0042", "Register service");
define("Service_0043", "In this table, list of services are shown ");
define("Service_0044", "Service has been removed successfully");
define("Service_0045", "Row");
define("Service_0046", "Service name");
define("Service_0047", "Speed");
define("Service_0048", "Periodic traffic");
define("Service_0049", "Amount of Periodic traffic volume");
define("Service_0050", "Total traffic volume");
define("Service_0051", "Number of connection days");
define("Service_0052", "Hourly service");
define("Service_0053", "Specified time period");
define("Service_0054", "End service");
define("Service_0055", "Agents");
define("Service_0056", "Tools");
define("Service_0057", "Remove service");
define("Service_0058", "Modify service");
define("Service_0059", "Default service");
define("Service_0060", "Remove default service");
define("Service_0061", "Before removing a service,please move the customers using this service to another service.");
define("Service_0062", "User service");
define("Service_0063", "Dismiss");
define("Service_0064", "Move service");
define("Service_0065", "Modify service");
define("Service_0066", "For modifying the desired service, fill in the form below");
define("Service_0067", "User service name");
define("Service_0068", "You can enter the amount of traffic volume in numbers.(Mb or Gb)");
define("Service_0069", "You can enter the total amount of traffic volume in numbers.(Mb or Gb)");
define("Service_0070", " NAS ID");
define("Service_0071", " NAS Name has been moved");
define("Service_0072", "Remove default service");
define("Service_0073", "Add default Nas");
define("Service_0080", "Choose speed");
define("Service_0074", "Total traffic volume");
define("Service_0075", "Register customer's information");
define("Service_0076", "Specified period in all days");
define("Service_0077", "Maximum time of connection to the internet");
define("Service_0078", "(Minute:Hour)");
define("Service_0079", "Valid time for accessing the internet from the first connection");
define("Service_0081", "General specifications");
define("Service_0082", "Traffic volume specifications");
define("Service_0083", "Time specifications");
define("Service_0084", "Periodic time");
define("Service_0085", "Daily");
define("Service_0086", "Weekly");
define("Service_0087", "Monthly");
define("Service_0088", "Day");
define("Service_0089", "Minute");
define("Service_0090", "Idle time");
define("Service_0091", "");
define("Service_0092", "Activate specified days");
define("Service_0093", "All days in a week");
define("Service_0094", "Services");
define("Service_0095", "periodic time");
define("Service_0096", "Amount of periodic time");
define("Service_0097", "Total time");
define("Service_0098", "Specified time in a specified day");
define("Service_0099", "Service expiration date");
define("Service_0100", "Periodic traffic volume");
define("Service_0101", "Time in hours");
//define("Service_0101", "نام کمپانی را درست وارد کنید");
define("Service_0102", "Please enter the service name");
define("Service_0103", "Please use English alphabets for service name");
define("Service_0104", "Please enter the speed, correctly.");
define("Service_0105", "Please enter the traffic, correctly.");
define("Service_0106", "Please enter the time, correctly.");
define("Service_0107", "Service name is duplicate");
define("Service_0108", "Edit structure is not correct");
define("Service_0109", "Enable");
define("Service_0110", "Available access time");
define("Service_0111", "Financial specifications");
define("Service_0112", "By entering the price, you can make a business service");
define("Service_0113", "Price   Toman ");
define("Service_0114", "Please enter the price, correctly.");
define("Service_0115", "Toman");
define("Service_0116", "Price");
define("Service_0117", "Please enter the password");
define("Service_0118", "Your password has been sent");
define("Service_0119", "Please enter the password, correctly.");
define("Service_0120", "Password must contain numbers and lower case letters");
define("Service_0121", "Advertisements");
define("Service_0122", "Concurrent connections");
define("Service_0123", "Number of concurrent connections: ");
define("Service_0124", "Periodic advertisements for connecting to the internet");
define("Service_0125", "Periodic advertisements");
define("Service_0126", "Period time");
define("Service_0127", "Minutes");
define("Service_0128", "Periodic time");
define("Service_0129", "Available access time");
define("Service_0130", "End of service");
define("Service_0131", "Enable");
define("Service_0132", "Day");
define("Service_0133", "Day1");
define("Service_0134", "Service");
define("Service_0135", "User");
define("Service_0136", "Your service edited successfully.");
define("Service_0137", "You can edit your service here.");
define("Service_0138", "This service is not removable because of public NAS ");
define("Service_0139", "Policy");
define("Service_0140", "Your policy field has some errors");
define("Service_0141", "usage report");
define("Service_0142", "You must know, that your previous volume will be removed after buying new service or change service.");


//admin.coupon.*.php Admin page
define("Coupon_0001", "Coupons");
define("Coupon_0002", "List of coupons");
define("Coupon_0003", "Add coupon");
define("Coupon_0004", "You can make desired number of coupons for your services.");
define("Coupon_0005", "Number of coupons");
define("Coupon_0006", "Please enter the number of coupons, correctly.");
define("Coupon_0007", "Please choose a service");
define("Coupon_0008", "Coupon");
define("Coupon_0009", "Expiry date");
define("Coupon_0010", "Coupon kind");
define("Coupon_0011", "Printed");
define("Coupon_0012", "Virtual");
define("Coupon_0013", "Please enter the money, correctly.");
define("Coupon_0014", "Please enter the date, correctly.");
define("Coupon_0015", "Please choose one of the kinds of coupons.");
define("Coupon_0016", "Coupon serial number");
define("Coupon_0017", "Creation date");
define("Coupon_0018", "Expiry date");
define("Coupon_0019", "Usage date");
define("Coupon_0020", "Creator");
define("Coupon_0021", "Service price");
define("Coupon_0022", "Coupon price");
define("Coupon_0023", "The first three digits of serial number.");
define("Coupon_0024", "Please enter the first digits of serial number, correctly.");
define("Coupon_0025", "Please enter the coupon, correctly.");
define("Coupon_0026", "Coupon is not usable.");
define("Coupon_0027", "Coupon was added successfully.");
define("Coupon_0028", "Remove package");
define("Coupon_0029", "Adding package to the company");
define("Coupon_0030", "Save");
define("Coupon_0031", "ID is not correct.");
define("Coupon_0032", "Removing package from the company");
define("Coupon_0033", "Buy service");
define("Coupon_0034", "Choose the desired service.");
define("Coupon_0035", "Change service");
define("Coupon_0036", "Service name is not correct.");
define("Coupon_0037", "Used");
define("Coupon_0038", "Coupon created successfully.");
define("Coupon_0039", "number of characters");
define("Coupon_0040", "");
define("Coupon_0041", "coupon");
define("Coupon_0042", "buy");
define("Coupon_0043", "Sorry! There is a problem in payment please retry later.");
define("Coupon_0044", "");
define("Coupon_0045", "");
define("Coupon_0046", "");
define("Coupon_0047", "");
define("Coupon_0048", "");
define("Coupon_0049", "");
define("Coupon_0050", "");


// pacakge creation
define("Package_0001", "Create package");
define("Package_0002", "You can use the form below to create a package.");
define("Package_0003", "Package name");
define("Package_0004", "Package price");
define("Package_0005", "Package type");
define("Package_0006", "General package");
define("Package_0007", "Single package");
define("Package_0008", "Package period(Month)");
define("Package_0009", "Number of messages");
define("Package_0010", "Number of calls");
define("Package_0011", "Number of users");
define("Package_0012", "Please enter the name, correctly.");
define("Package_0013", "Enter package period, correctly.");
define("Package_0014", "Please enter the number of messages,Correctly");
define("Package_0015", "Please enter the number of calls, correctly.");
define("Package_0016", "Please enter the number of users, correctly.");
define("Package_0017", "List of packages");
define("Package_0018", "Modify package");
define("Package_0019", "Please enter the group, correctly");
define("Package_0020", "Package expiry date");
define("Package_0021", "Package");
define("Package_0022", "Count from expiry date");
define("Package_0023", "Numbers");
define("Package_0024", "Start time after payment");
define("Package_0025", "Start time of current package");
define("Package_0026", "Expiry date after buying");
define("Package_0027", "Expiry date of current package");
define("Package_0028", "Salable");
define("Package_0029", "This package is not for this company.");
define("Package_0030", "Installment");
define("Package_0031", "Payment was not successful.");
define("Package_0032", "Add package group to company");
define("Package_0033", "Package group was added to company, successfully.");
define("Package_0034", "You can not add asingle package before adding a general package.");
define("Package_0035", "When package time finishes, you can just buy a general package.");
define("Package_0036", "Your invoice is empty");
define("Package_0037", "You can just have one general package.");
define("Package_0038", "Hello");
define("Package_0039", "You just have");
define("Package_0040", "in your Netband");
define("Package_0041", "Please add");
define("Package_0042", "to your Netband");
define("Package_0043", "Thank you ");
define("Package_0044", "Your Netband in package will expire in");
define("Package_0045", "days");
define("Package_0046", "Please extend package. ");
define("Package_0047", "Remove package group from company");
define("Package_0048", "Package group was added to the company, successfully.");
define("Package_0049", "Value added tax(Rial)");
define("Package_0050", "Total(Rial)");
define("Package_0051", "Dear manager");
define("Package_0052", "Package added to company");

// create company group
define("groupCompany_0001", "Create company group");
define("groupCompany_0002", "Group name");
define("groupCompany_0003", "List of company group");
define("groupCompany_0004", "Modify company group");
define("groupCompany_0005", "Creation date");
define("groupCompany_0006", "Update date");
define("groupCompany_0007", "Updated by");
define("groupCompany_0008", "Role");
define("groupCompany_0009", "Member");
define("groupCompany_00010", "Manager");
define("groupCompany_00011", "Show group company members");
define("groupCompany_00012", "Add company to group");
define("groupCompany_00013", "Remove company from group");
define("groupCompany_00014", "List of general packages of company");
define("groupCompany_00015", "List of single packages of company");
define("groupCompany_00016", "Are you sure you want to delete the company from group?");
define("groupCompany_00017", "Are you sure you want to delete the company?");
define("groupCompany_00018", "Your Netband package has expired.");
define("groupCompany_00019", "");
define("groupCompany_00020", "");
define("groupCompany_00021", "");
define("groupCompany_00022", "");
define("groupCompany_00023", "");
define("groupCompany_00024", "");
define("groupCompany_00025", "");
define("groupCompany_00026", "");
define("groupCompany_00027", "");
define("groupCompany_00028", "");
define("groupCompany_00029", "");
define("groupCompany_00030", "");


// create group package
define("groupPackage_0001", "Create package group");
define("groupPackage_0002", "Package group name");
define("groupPackage_0003", "Package group list");
define("groupPackage_0004", "Modify package group");
define("groupPackage_0005", "Package group");
define("groupPackage_0006", "Call");
define("groupPackage_0007", "Remaining");
define("groupPackage_0008", "SMS");
define("groupPackage_0009", "Company of packages used");
define("groupPackage_00010", "Add to basket");
define("groupPackage_00011", "Show members of package group");
define("groupPackage_00012", "Add package to group");
define("groupPackage_00013", "Remove package from group");

define("companyPackage_0001", "Create company package");
define("companyPackage_0002", "Company's package name");
define("companyPackage_0003", "List of the packages of the company");
define("companyPackage_0004", "Modify company package");
define("companyPackage_0005", "Company's package");
define("companyPackage_0006", "Daily traffic volume (MB)");
define("companyPackage_0007", "Owner");
define("companyPackage_0008", "Company's package log");
define("companyPackage_0009", "");
define("companyPackage_00010", "");
define("companyPackage_00011", "Show members of the company's package");
define("companyPackage_00012", "Add package to company");
define("companyPackage_00013", "Remove package from company");

define("Payment_0001", "List of payments");
define("Payment_0002", "User information");
define("Payment_0003", "Payment method");
define("Payment_0004", "Details");
define("Payment_0005", "or");
define("Payment_0006", "Invoice");
define("Payment_0007", "Add to invoice");
define("Payment_0008", "Back to management page");
define("Payment_0009", "Success");
define("Payment_00010", "Transaction did not succeed");
define("Payment_00011", "Your transaction ID");
define("Payment_00012", "Transaction succeeded.");
define("Payment_00013", "is");
define("Payment_00014", "All the legal expenses for buying has been calculated in the price.");
define("Payment_00015", "Users are not part of a company.");
define("Payment_00016", "Support tel : 02122435200");
define("Payment_00017", "Back to Factor");
define("Payment_00018", "An error occurred when connecting to Saman bank web service");
define("Payment_00019", "There was a problem in the transaction from suppliers.");
define("Payment_00020", "");
define("Payment_00021", "usage amount");
define("Payment_00022", "cancel");
define("Payment_00023", "The payment canceled by user.");
define("Payment_00024", "The payment done correctly.");
define("Payment_00025", "ُSorry! There is a problem in payment please try again.");

//setting.php admin page
define("Setting_001", " Setting");
define("Setting_002", "Edit system users");
define("Setting_003", "Permission");
define("Setting_004", "Manage system users");
define("Setting_005", "Passwords do not match.");
define("Setting_006", "Password has been changed successfully.");
define("Setting_007", "Changed permission");
define("Setting_008", "Can not connect to the database");
define("Setting_009", "Modify password for system users");
define("Setting_010", "Modify access level for system users");
define("Setting_011", "System users list");
define("Setting_012", "Modify system user");
define("Setting_013", "Website setting");
define("Setting_014", "Forms setting");
define("Setting_015", "Social Network link setting");
define("Setting_016", "Register form setting");
define("Setting_017", "Operation done Successfully.");
define("Setting_018", "Company's welcome message");
define("Setting_019", "Apply changes");
define("Setting_020", "Welcome message before company name");
define("Setting_021", "Welcome message after company name");
define("Setting_022", "Text for support Tel");
define("Setting_023", "Text for support site");
define("Setting_024", "Information has been updated successfully.");
define("Setting_025", "Add Text Input");
define("Setting_026", "Add the form");
define("Setting_027", "This field has deleted successfully.");
define("Setting_028", "This field has modified successfully.");

//admin.customer.*.php Admin page
define("User_001", " Users");
define("User_002", "In this table, all the users of the system are shown");
define("User_003", "System users");
define("User_004", "Choose");
define("User_005", "Client name");
define("User_006", "User name");
define("User_007", "Email");
define("User_008", "User service");
define("User_009", "Lock");
define("User_0010", "Tools");
define("User_0011", "Service has been changed successfully");
define("User_0012", "SMS");
define("User_0013", "Modify user mode");
define("User_0014", "Delete user");
define("User_0015", "Add Traffic volume");
define("User_0016", "Renew service");
define("User_0017", "Resend password");
define("User_0018", "Are you sure you want to delete the chosen client?");
define("User_0019", "Dismiss");
define("User_0020", "Increase user's traffic volume");
define("User_0021", "Choose one of these traffic volumes");
define("User_0022", "Traffic volume");
define("User_0023", "Confirm");
define("User_0024", "Change client's service");
define("User_0025", "Enter the new service for the desired user.");
define("User_0026", "Resend client's password");
define("User_0027", "Choose one of the methods for resending password.");
define("User_0028", "Send password via SMS");
define("User_0029", "Send SMS");
define("User_0030", "Send SMS to users");
define("User_0031", "Entered numbers");
define("User_0032", "SMS text");
define("User_0033", "Send");
define("User_0034", "Online clients are shown in this table.");
define("User_0035", "Kick");
define("User_0036", "1 GB");
define("User_0037", "3 GB");
define("User_0038", "5 GB");
define("User_0039", "10 GB");
define("User_0040", "15 GB");
define("User_0041", "Register new user");
define("User_0042", "Registering a new user is one of the facilities by this form ");
define("User_0043", "Client has been registered successfully.");
define("User_0044", "Name");
define("User_0045", "Email");
define("User_0046", "Telephone number");
define("User_0047", "Confirm form and save information");
define("User_0048", "For identifying the user and confirming user information,choose one of the options below and press the send button.The password will be sent to user. ");
define("User_0049", "Send password via voice Message");
define("User_0050", "Password");
define("User_0051", "Send password");
define("User_0052", "Register client");
define("User_0053", "Choose");
define("User_0054", "Remove client");
define("User_0055", "Choose internet traffic volume");
define("User_0056", "Traffic increment has been done successfully.");
define("User_0057", "Log Report");
define("User_0058", "In this table, users log report is shown .");
define("User_0059", "Client log report");
define("User_0060", "Choose service");
define("User_0061", "Register date");
define("User_0062", "Change password");
define("User_0063", "Old password");
define("User_0064", "New password");
define("User_0065", "Re-type new password");
define("User_0066", "If you do not enter a password, the system will generate a random password and will send it to the desired user.");
define("User_0067", "Renew service");
define("User_0068", "Change service");
define("User_0069", "Number of concurrent connections");
define("User_0070", "Enter the number of concurrent connections for the desired user.");
define("User_0071", "Number of devices");
define("User_0072", "Password reminder");
define("User_0073", "Your username or password is wrong.");
define("User_0074", "User's Number");
define("User_0075", "Change user's service");
define("User_0076", "Select all");
define("User_0077", "Are you sure you want to lock this user?");
define("User_0078", "Are you sure you want to kick this user?");
define("User_0079", "User profile");
define("User_0080", "User profile");
define("User_0081", "Service information");
define("User_0082", "Connection information");
define("User_0083", "Connection time");
define("User_0084", "Disconnection time");
define("User_0085", "Volume used");
define("User_0086", "Customer has been deleted successfully.");
define("User_0087", "There was a problem deleting the customer, please contact support.");
define("User_0088", "Service was renewed successfully.");
define("User_0089", "NAS name");
define("User_0090", "Please fill in this field");
define("User_0091", "additional info");
define("User_0092", "name");
define("User_0093", "value");
define("User_0094", "customer detail");
define("User_0095", "Please try again.");
define("User_0096", "Register confirmation");
define("User_0097", "Confirm and register");
define("User_0098", "Cancel and enter the new information");
define("User_0099", "کاربران اپلیکیشن موبایل");
define("User_0100", "عنوان");
define("User_0101", "تصویر");
define("User_0102", "لینک");
define("User_0103", "User Usage Report");

//admin.report.*.php Admin page
define("Report_001", "No result was found.");
define("Report_002", "Report of the changes in users service");
define("Report_003", "In this table Report of the changes of users service is shown");
define("Report_004", "Row");
define("Report_005", "User ID");
define("Report_006", "Previous service");
define("Report_007", "New service");
define("Report_008", "Date");
define("Report_009", "User report");
define("Report_0010", "In this table, traffic and usage time are shown.");
define("Report_0011", "Users status report");
define("Report_0012", "from");
define("Report_0013", "until");
define("Report_0014", "Search");
define("Report_0015", "Connection time");
define("Report_0016", "End time");
define("Report_0017", "Usage time");
define("Report_0018", "Traffic volume used");
define("Report_0019", "Branch");
define("Report_0020", "Time is not specified");
define("Report_0021", "Online user");
define("Report_0022", "Report of increment in users traffic volume");
define("Report_0023", "In this table all the clients of the system are shown.");
define("Report_0024", "Change Users service");
define("Report_0025", "Traffic volume");
define("Report_0026", "In this table all the kick and Lock of users are shown");
define("Report_0027", "Name");
define("Report_0028", "Kick");
define("Report_0029", "Lock");
define("Report_0030", "Response (Server)");
define("Report_0031", "Status");
define("Report_0032", "Hour");
define("Report_0033", "Real-time report");
define("Report_0034", "In this table all the services of clients are shown");
define("Report_0035", "No result was found.");
define("Report_0036", "Users Kick and Lock report");
define("Report_0037", "Archive of Report of users' usage");
define("Report_0038", "In this table, traffic archive and usage time are shown.");
define("Report_0039", "Traffic");
define("Report_0040", "Lock/Kick");
define("Report_0041", "Admin name");
define("Report_0042", "Admin ID");
define("Report_0043", "Traffic volume used");
define("Report_0044", "Stop");
define("Report_0045", "Company name");
define("Report_0046", "Customer");
define("Report_0047", "Receiving company");
define("Report_0048", "Text");
define("Report_0049", "Kind");
define("Report_0050", "Creation date");
define("Report_0051", "Section");
define("Report_0052", "Sender company");
define("Report_0053", "Price");
define("Report_0054", "Kind");
define("Report_0055", "Service name");
define("Report_0056", "Creation date");
define("Report_0057", "Serial number");
define("Report_0058", "Status");
define("Report_0059", "Payment");
define("Report_0060", "Type");
define("Report_0061", "Service name");
define("Report_0062", "Creation date");
define("Report_0063", "Serial number");
define("Report_0064", "Tools");
define("Report_0065", "Admin last name");
define("Report_0066", "Filter for report");
define("Report_0067", "From");
define("Report_0068", "To");
define("Report_0069", "Start");
define("Report_0070", "Tracking number");
define("Report_0071", "Reference number");
define("Report_0072", "Package name");
define("Report_0073", "Buyer company");
define("Report_0074", "Transaction date");
define("Report_0075", "Paying company");
define("Report_0076", "User name");
define("Report_0077", "Number of connections");
define("Report_0078", "Date of first connection");
define("Report_0079", "Date of last disconnection");
define("Report_0080", "Select All");
define("Report_0081", "Number of devices");
define("Report_0082", "Mobile customers");
define("Report_0083", "Remind volume");
define("Report_0084", "The service has been used. ");
//Message
define("Message_001", "Number of characters before password");
define("Message_002", "Number of characters after password");
define("Message_003", "Page");
define("Message_004", "Complete text");
define("Message_005", "Your Netband password is");
define("Message_006", "Number of characters.");

//admin.Advertisment.*.php Admin page
define("Advertisment_001", "Name is not valid");
define("Advertisment_002", "Extension is not valid");
define("Advertisment_003", "Specify a view location");
define("Advertisment_004", "Priority can only be chosen by numbers");
define("Advertisment_005", "Language has not been chosen correctly");
define("Advertisment_006", "The website address is not correct");
define("Advertisment_007", "Comments have not been entered correctly");
define("Advertisment_008", "Image has not been entered");
define("Advertisment_009", "Add advertisement");
define("Advertisment_0010", "Ad name");
define("Advertisment_0011", "Ad place");
define("Advertisment_0012", "Up");
define("Advertisment_0013", "Down");
define("Advertisment_0014", "View Priority");
define("Advertisment_0015", "Link Address");
define("Advertisment_0016", "Language");
define("Advertisment_0017", "Persian");
define("Advertisment_0018", "English");
define("Advertisment_0019", "Comments");
define("Advertisment_0020", "Advertisement Banner");
define("Advertisment_0021", "Select file");
define("Advertisment_0022", "Change");
define("Advertisment_0023", "Submit Form");
define("Advertisment_0024", "Modify advertisement");
define("Advertisment_0025", "Manage advertisements");
define("Advertisment_0026", "Child ad");
define("Advertisment_0027", "URL");
define("Advertisment_0028", "Modify advertisement mode");
define("Advertisment_0029", "Subset advertisement");
define("Advertisment_0030", "In this table, child advertisement is shown");
define("Advertisment_0031", "Child advertisement");
define("Advertisment_0032", "Choose image");
define("Advertisment_0033", "Add child advertisement");
define("Advertisment_0034", "Add sub advertisement");
define("Advertisment_0035", "Add advertisements");
define("Advertisment_0036", "List of advertisements");
define("Advertisment_0037", "In this table, list of advertisements is shown");
define("Advertisment_0038", "Show Image");
define("Advertisment_0039", "View place");
define("Advertisment_0040", "Priority");
define("Advertisment_0041", "View child");
define("Advertisment_0042", "Remove advertisement");
define("Advertisment_0043", "Modify sub advertisement");
define("Advertisment_0044", "Remove sub advertisement");
define("Advertisment_0045", "Added Successfully");
define("Advertisment_0046", "Sorry, there is a problem to submit this advertisement. Call support.");
define("Advertisment_0047", "Image was not attached.");
define("Advertisment_0048", "file extension is not allowed");
define("Advertisment_0049", "Image has been attached");

//companyMenu
define("companyMenu_0010", "Name menu item ");
define("companyMenu_0011", "price ");
define("companyMenu_0012", "Sorry, there is a problem to submit this menu item. Call support.");
define("companyMenu_0013", "Edit item  ");
define("companyMenu_0014", "Delete item  ");
define("companyMenu_0016", "Menu");

//admin.adminlist.*.php Admin page
define("adminList_001", "Are you sure?");
define("adminList_002", "Access Control");
define("adminList_003", "Register operator");
define("adminList_004", "Family name");
define("adminList_005", "Password");
define("adminList_006", "Repeat Password");
define("adminList_007", "Add new admin");
define("adminList_008", "List of operators");
define("adminList_009", "Company name");
define("adminList_0010", "Operations");
define("adminList_0011", "View Access level ");
define("adminList_0012", "Complete page");
define("adminList_0013", "Open and close");
define("adminList_0014", "Remove");
define("adminList_0015", "Modify");
define("adminList_0016", "Defining access levels");
define("adminList_0017", "Dismiss");
define("adminList_0018", "Confirm");
define("adminList_0019", "Modify operator's information");
define("adminList_0020", "Modify operators");
define("adminList_0021", "Creation date");
define("adminList_0022", "Users report");
define("adminList_0023", "Report of increment in users traffic volume");
define("adminList_0024", "Real time report of users");
define("adminList_0025", "Users log report");
define("adminList_0026", "Report of increment in users traffic volume");
define("adminList_0027", "Lock & Kick report");
define("adminList_0028", "Report of users usage");
define("adminList_0029", "Users list");
define("adminList_0030", "List of online users");
define("adminList_0031", "Add new user");
define("adminList_0032", "Users information bank");
define("adminList_0033", "Send advertisement messages for users");
define("adminList_0034", "Resend password");
define("adminList_0035", "Change service");
define("adminList_0036", "Add volume");
define("adminList_0037", "Delete user");
define("adminList_0038", "Service list");
define("adminList_0039", "Add new service");
define("adminList_0040", "Modify service");
define("adminList_0041", "Move and delete service");
define("adminList_0042", "Purchasing service");
define("adminList_0043", "List of sets");
define("adminList_0044", "List of branches");
define("adminList_0045", "Users advertisements");
define("adminList_0046", "Companies advertisements");
define("adminList_0047", "About us");
define("adminList_0048", "Contact us");
define("adminList_0049", "Contact us");
define("adminList_0050", "Coupon list");
define("adminList_0051", "Show companies packages");
define("adminList_0052", "View List");
define("adminList_0053", "Add Admin");
define("adminList_0054", "Edit Admin");
define("adminList_0055", "Remove Admin");
define("adminList_0056", "Set Task");
define("adminList_0057", "Permissions were successfully assigned to the Director");
define("adminList_0058", "Your request can not be done");
define("adminList_0059", "Admin is not available in the list");
define("adminList_0060", "You do not have access to the Administrator");
define("adminList_0061", "Admin was successfully removed from the list");
define("adminList_0062", "Passwords do not match!");
define("adminList_0063", "Admin details edited successfully.");
define("adminList_0064", "Admin was successfully added to the list and is available!");
define("adminList_0065", "Password Must be between 6 and 20 Characters!");
define("adminList_0066", "Please enter Password!");
define("adminList_0067", "Admin Username must be between 4 and 20 Characters!");
define("adminList_0068", "Please enter the administrator username!");
define("adminList_0069", "This username is in the list!");
define("adminList_0070", "show Sub Company");
define("adminList_0071", "policy");

//admin.page.*.php Admin page
define("adminPage_001", "Information about us");
define("adminPage_002", "In this section you can change the About Us text of the site");
define("adminPage_003", "Open");
define("adminPage_004", "Close");
define("adminPage_005", "Modify text");
define("adminPage_006", "Meta tag");
define("adminPage_007", "Enter with comma");
define("adminPage_008", "Meta tag with comma");
define("adminPage_009", "Operation done successfully");
define("adminPage_0010", "Message");
define("adminPage_0011", "Message writer");
define("adminPage_0012", "Insertion date");
define("adminPage_0013", "Reading");
define("adminPage_0014", "Remove");
define("adminPage_0015", "Read");
define("adminPage_0016", "Text message");
define("adminPage_0017", "Please enter your name");
define("adminPage_0018", "Please enter the text message");
define("adminPage_0019", "Please enter your Email address");
define("adminPage_0020", "Not read");
define("adminPage_0021", "Tools");
define("adminPage_0022", "Message was sent.");
define("adminPage_0023", "File was attached");
define("adminPage_0024", "File format is not acceptable.");
define("adminPage_0025", "File");
define("adminPage_0026", "Delete message");
define("adminPage_0027", "Subject");
define("adminPage_0028", "Menu");

define("Website_001", "Website ");
define("Website_002", "Update ");

define("Help", "Guide");
define("Helper_001", "Show all ...");


define("INSERT_PHONE", "Enter your mobile phone number(Use English font)");
define("INSERT_PASSWORD", "Enter your password");
define("FORGET_PASSWORD", "If you forgot your password, you can retrieve your password with the options below.");
define("INSERT_NAME", "Enter your name");
define("INSERT_LASTNAME", "Enter your family name");
define("INSERT_EMAIL", "Enter your Email");
define("SEND", "To register push this button");


define("LOGIN_USERNAME", "Enter your User ID");
define("LOGIN_PASSWORD", "Enter your Password");
define("LOGIN_USERNAME1", "Username is not valid");
define("LOGIN_PASSWORD1", "Password is not valid");


define("ALL_USER", "All users");
define("ALL_ONLINE_USER", "Online users");
define("ALL_USER1", "In this chart you can see the number of users who login or register");
define("ALL_USER2", "In this chart you can see the total traffic volume in a day");

define("MESSAGE_CONTENT", "Content of sent message");
define("MESSAGE_EMAIL", "Sender's Email");
define("MESSAGE_DATE", "Issue date");
define("MESSAGE_READ", "If you read the message, click on the relevant button");
define("MESSAGE_DELETE", "If you need to remove message, click on the relevant button");

define("ENGLISH", "Insert text in English");
define("PERSIAN", "Insert text in Persian");

define("OWNER_ADD", "In this section you can add an operator");
define("OWNER_LIST", "List of added operators. You can remove, modify, delete or change operator's access level in operation section.");

define("ADS_LIST", "In this table the list of advertisements are shown ");
//define("ADS_ADD", "Using the form below you can add an advertisement");

define("USER_ONLINE_STORAGE", "In this section with start and end date, you can view the user's usage");
define("USER_ONLINE_LIST", "You can view users list in this section");
define("USER_STORAGE", " List of all users that had traffic increment.");
define("USER_STATUS_NOW_STOP", "With this button you can stop the reload");
define("USERS_ONLINE", "Live view of online users");
define("USER_NAME", "Insert name for a specified user");
define("USER_START_DATE", "Date range from");
define("USER_END_DATE", "Date range until");
define("USER_LOG_LIST", "In this table the report of users log is viewed.");
define("USER_CHANGE_SERVICE", "Report of changes in user's service");
define("USER_KICK_LOCK", "List of users who have been kicked and locked");

define("COMP_EN_NAME", "Company name in English");
define("COMP_FA_NAME", "Company name in Persian");
define("COMP_ID", "Company ID");
define("COMP_STATUS", "Current status of company");
define("COMP_ADMIN_NAME", "Manager's username");
define("COMP_ADMIN_USER", "Manager's User ID");
define("COMP_ADDRESS", "Address");
define("COMP_PHONE_NUMBER", "Contact number");
define("COMP_URL", "Website Address");
define("COMP_EMAIL", "Email");
define("COMP_EMAIL_Supp", "Backup Email(Users messages are sent to this E-mail)");
define("COMP_DETAIL", "Required comments");
define("COMP_TOOLS", "Tools for making modifications in companies");
define("COMP_PASS", "Password for management panel");
define("COMP_PASS2", "Repeat password for management panel");
define("COMP_LOGO", "Company's logo");
define("COMP_TELEPHONE", "Company Number");

define("NAS_LIST", "View and modify existing Nas");
define("NAS_ADD", "With this form you can define a Nas");
define("NAS_EDIT", "With this form you can modify the chosen Nas ");

define("SERVICE_LIST", "All existing services");
define("SERVICE_NAME", "Insert service name");
define("SERVICE_STORAGE", "Traffic usage in a period");
define("SERVICE_SPEED", "Define service speed");
define("SERVICE_ALL", "Define the whole usable traffic");
define("SERVICE_DAY", "Number of active days for service");
define("SERVICE_TIME", "Define time in hours");
define("SERVICE_SELECT_DAY", 'Define days and times relevant to days for making a service ');
define("SERVICE_SELECT_ALL_DAY", "Define a specified time for all days ");
define("SERVICE_END", "Define the end time of service");

define("SMS", "Send SMS");
define("REVIVALSERVICE", "Renew service");
define("CHANGESERVICE", "Change service");
define("EXPORTEXCEL", "Excel");
define("LOCK", "Block user (The user can not login again)");
define("CUSTOMER", "Users list");
define("PUSH_NOTIFICATION", "Push notification ");


define("ADS_ADD", "By using this form you can add an advertisement and do the necessary configurations");

define("CUS_ADD", "By using this form you can add a new user");
define("CUS_SERIVCE", "By using this option, you can define service type for user ");

define("KICK", "Kick user (The user will get disconnected but can login again)");
define("INDEX_ERROR", "For viewing the login page, use a site. For example use Google.");

define("ERROR404", "The page that you requested was not found.");
define("ERROR4041", "404");
define("ERROR201", "202");
define("ERROR2011", "Your service is not available now, please call support.");

//coupon login **********
define("couponLogin_01", "view coupons");
define("couponLogin_02", "Add coupon");
define("couponLogin_03", "Remove coupon");
define("couponLogin_04", "Member`s coupon");
define("couponLogin_05", "coupon customer list");
define("couponLogin_06", "coupon report");
define("couponLogin_07", "volume report");
define("couponLogin_08", "Increase Volume");
define("couponLogin_09", "extend service");
define("couponLogin_10", "create new coupon user");
define("couponLogin_11", "In this page you can register your desired user");
define("couponLogin_12", "coupon number");
define("couponLogin_13", "coupon user register form setting");



define("phoneLogin", "PhoneNumber login");
define("couponLogin", "Coupon Login");
define("coupon_01", "Please enter your coupon number for login.");
define("coupon_02", "your coupon used before.");
define("coupon_03", "Please enter your coupon number correctly.");
define("coupon_04", "phone number");
define("coupon_05", "traffic size successfully changed");
define("coupon_06", "Increase the volume of traffic is only for traffic-service");
define("coupon_07", "successfully added");
define("coupon_08", "successfully extended");
define("coupon_09", "Please choose one of the users");
define("coupon_10", "enter your coupon number");
define("coupon_11", "a problem has been occurred. Please try again or contact support");
define("coupon_12", "your account has been disabled");


define("couponRegister_01", "enter your name");
define("couponRegister_02", "enter your family name");
define("couponRegister_03", "enter your phone number");
define("couponRegister_04", "enter your email");
define("couponRegister_05", "enter your bithday");
define("Register_06", "Your information is not complete for this company. please fill register form again.");
define("YouAreLogIn","You have log in");

define("event_not_found","Event not found");
define("salon_not_found","Salon not found");
define("Position_not_found_with_this_salon","Position not found whit this salon");
define("position_not_found","Position not found");
define("not_exists_chair","Not exists chair");
define("add_ticket","Add ticket to cart");
define("invoice_not_found","Invoice not found");
define("success","Successfully");
define("register_successfully","Register successfully.");
define("email_is_not_valid","Email is not valid.");


define("info_login","Please enter your information fo login.");
define("email_or_number","Email or mobile:");
define("number_or_email","Mobile / Email:");
define("password","Password: ");
define("login","Login");
define("register","Register");
define("forgot_password","Forgot password?");
define("login_by_account","I have account");
define("Password_sent","Password sent.");
define("create_new_account","Create new account");
define("mobile","Mobile (exe:9193110190):");
define("name_fa","Name and family(persian):");
define("name_en","Name and family(english):");
define("email","Email");
define("are_you_artists_please_click_here","Are you an artist please click here");
define("birthday","Birthday:");
define("show_birthday_for_public","Show birthday for public");
define("category","Group: ");
define("category_arrow_down","Group ");
define("genre","Genre: ");
define("genre_arrow_down","Genre ");
define("site","Site: ");
define("instagram","Instagram:");
define("sound_cloud","Sound cloud: ");
define("beeptunes","Beeptunes: ");
define("facebook","Facebook: ");
define("telegram","Telegram: ");
define("bio_fa","Biography(persian): ");
define("bio_en","Biography(english): ");
define("own_image","Picture");
define("picture_is_square_and_jpeg","Picture is square by jpg format");
define("category_id_not_empty","Category id is not empty");
define("password_not_empty","Password is not empty");
define("please_login_before_choose_chair","Please login before choose chair ");

define("wait_to_send","Wait To Send ...");
define("canceled_by_user","Canceled by user");
define("return_back_to_account","back to account");
define("pay_not_success","pay not success");
define("pay_success","pay success");
define("pay_result","pay result");

define("invoices","Invoices");
define("invoice_time","Time: ");
define("invoice_place","Location: ");
define("price","Price: ");
define("rial","Rial");
define("sandali_number","Place");
define("pay_by_eghtesad_novin","Pay by eghtesad novin");
define("delete_invoice","delete invoice");
define("description_fa","Persian description:");
define("description_en","English description:");
define("telephone","Telephone");
define("image","Image");
define("edit","Edit");
define("edited_password_if_filling","Edited password if filling this field");

define("event_name_fa","Event Name (fa)");
define("event_name_en","Event Name (en)");
define("event_time","Event time");
define("new_event","New event");
define("event_date","Event date");
define("city","City");
define("address_fa","Address (fa)");
define("address_en","Address (en)");
define("submit","Submit");

define("your_event_has_been_recorded","Your event has been recorded");
define("sanladi_number","numbers");

define("persian_name_is_empty","Persian name is empty");
define("latin_name_is_empty","Latin name is empty");
define("email_is_empty","Email is empty");